-- AlterTable
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "telegramPhotoUrl" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "telegramLang" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "telegramPremium" BOOLEAN DEFAULT false;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "telegramAllowsPm" BOOLEAN DEFAULT false;
