FROM node:24-slim

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends openssl libvips && rm -rf /var/lib/apt/lists/*

COPY package*.json ./
RUN npm ci

COPY . .

EXPOSE 3001
